import { defineConfig } from "cz-git";

export default defineConfig({
  extends: ["@commitlint/config-conventional"],
  rules: {
    "subject-empty": [2, "never"],
    "header-max-length": [2, "always", 100],
  },
  prompt: {
    alias: { fd: "docs: fix typos" },
    messages: {
      type: "请选择本次提交的变更类型：",
      scope: "请选择此次变更的范围（可选）：",
      customScope: "请输入此次变更的范围：",
      subject: "请简短直接地描述本次变更：\n",
      body: '请提供更详细的变更描述（可选），使用 "|" 换行：\n',
      breaking: '列出所有破坏性变更（可选），使用 "|" 换行：\n',
      footerPrefixesSelect: "请选择与本次变更相关的 Issue 类型（可选）：",
      customFooterPrefix: "请输入 Issue 前缀：",
      footer: "列出与本次变更关联的 Issue，例如：#31、#34：\n",
      generatingByAI: "正在通过 AI 生成提交说明...",
      generatedSelectByAI: "请选择一个合适的 AI 生成的提交标题：",
      confirmCommit: "确定要使用以上信息提交吗？",
    },
    types: [
      {
        value: "feat",
        name: "feat:     ✨  新功能",
        emoji: ":sparkles:",
      },
      { value: "fix", name: "fix:      🐛  修复 Bug", emoji: ":bug:" },
      {
        value: "docs",
        name: "docs:     📝  文档变更",
        emoji: ":memo:",
      },
      {
        value: "style",
        name: "style:    🎨  代码格式变化",
        emoji: ":lipstick:",
      },
      {
        value: "refactor",
        name: "refactor: ♻️   重构代码",
        emoji: ":recycle:",
      },
      {
        value: "perf",
        name: "perf:     ⚡️  优化代码",
        emoji: ":zap:",
      },
      {
        value: "test",
        name: "test:     ✅  测试相关",
        emoji: ":white_check_mark:",
      },
      {
        value: "build",
        name: "build:    📦️   构建/依赖变更",
        emoji: ":package:",
      },
      {
        value: "ci",
        name: "ci:       🎡  CI 配置变更",
        emoji: ":ferris_wheel:",
      },
      {
        value: "chore",
        name: "chore:    🔨  杂项/脚本",
        emoji: ":hammer:",
      },
      {
        value: "revert",
        name: "revert:   ⏪️  回滚提交",
        emoji: ":rewind:",
      },
    ],
    useEmoji: true,
    emojiAlign: "center",
    useAI: false,
    aiNumber: 1,
    themeColorCode: "",
    scopes: ["global", "frontend", "backend"],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: "bottom",
    customScopesAlias: "custom",
    emptyScopesAlias: "empty",
    upperCaseSubject: null,
    markBreakingChangeMode: false,
    allowBreakingChanges: ["feat", "fix"],
    breaklineNumber: 100,
    breaklineChar: "|",
    skipQuestions: [],
    issuePrefixes: [
      { value: "closed", name: "closed:   ISSUES has been processed" },
    ],
    customIssuePrefixAlign: "top",
    emptyIssuePrefixAlias: "skip",
    customIssuePrefixAlias: "custom",
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    scopeOverrides: undefined,
    defaultBody: "",
    defaultIssues: "",
    defaultScope: "",
    defaultSubject: "",
  },
});
